package/nodejs: drop support for the MIPS architecture
The build of NodeJS fails on mipsel due to an issue in the V8 code:

../../deps/v8/src/compiler/backend/mips/code-generator-mips.cc:4106:48: error: call of overloaded 'Operand(int64_t)' is ambiguous
 4106 |                 Operand(static_cast<int64_t>(0)));

There is apparently a lack of maintenance of the MIPS port of V8, as
is discussed in the Github issue at
https://github.com/nodejs/node/issues/26179.

Until this get improved/fixed, our best option is to drop support for
MIPS in our NodeJS package.

Fixes:

  http://autobuild.buildroot.net/results/0e6ee80c77bcb77afe18410e8d9da93b738cb0a4/

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>