package/libyang: needs __sync_*_4 intrinsics
libyang needs __sync_*_4 intrinsics since bump to version 2.0.112 in
commit 2877f70a78d65331816dd7b9c60878027ce029a5 and
https://github.com/CESNET/libyang/commit/080064b7906aecd7454e58e1c34c1c2198809e4e:

/home/buildroot/autobuild/instance-3/output-1/host/opt/ext-toolchain/bin/../lib/gcc/sparc-buildroot-linux-uclibc/9.3.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: ../../libyang.so.2.13.7: undefined reference to `__sync_fetch_and_sub_4'

Fixes:
 - http://autobuild.buildroot.org/results/c1f090bde4891ac1cc84e59c51ff9561869d42b9

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>