package/sconeserver: fix build with gcc 4.8
Fix the following build failure with gcc 4.8 raised since the addition
of -std=c++11 in commit 0e31abcdd8cb438dcd55e049483a427077d6585c:

sconex.cpp: In function 'scx::Date& scx::build_time()':
sconex.cpp:52:36: error: unable to find string literal operator 'operator"" __TIME__'
   static Date s_build_time(__DATE__" "__TIME__,true);
                                    ^

Fixes:
 - http://autobuild.buildroot.org/results/83ecf772965b4586eaea2682871a85732df7d62f

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>