package/pipewire-media-session: needs alsa-lib-ucm
Fix the following build failure raised since the addition of the
package in commit a98bfcc7a93bc87b7133eb898b048af66e8703d0:

../src/alsa-endpoint.c:34:10: fatal error: alsa/use-case.h: No such file or directory
   34 | #include <alsa/use-case.h>
      |          ^~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/bbf54d1bdb0f8f2d4f675ffdcbcbbf56562c3d7b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>