package/python-django-enumfields: needs python3
python2 support has been dropped since version 2.0.0 and
https://github.com/hzdg/django-enumfields/commit/3a9f92d67b15d1ae57ef7fb087858b5597413f30
resulting in the following build failure since bump to version 2.1.1 in
commit add643e3094ca73d98d22eeddd79c5829b9857e9:

error:   File "/usr/lib/python2.7/site-packages/enumfields/fields.py", line 134
    *super().check(**kwargs),
    ^
SyntaxError: invalid syntax

Fixes:
 - http://autobuild.buildroot.org/results/3fd79ed7bbcad202fc7ac07252cdf57c599dac30

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>