package/boost: fix boost-log build
Fix the following build failure with boost-log raised since bump to
version 1.79.0 in commit ffb1fab82f70637ea35444656a3090e31d3da5ec and
https://github.com/boostorg/log/commit/3cbc2585c3b7ff5d884a6c337a99525b57fa184b:

error: at libs/log/build/Jamfile.v2:59
error: Unable to find file or target named
error:     '/boost/architecture//mips'
error: referred to from project at
error:     'libs/log/build'

Fixes:
 - http://autobuild.buildroot.org/results/edcc7c7f3586993a77b6cc06ed02363a42c09a83

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>