package/janet: needs gcc >= 4.9
janet needs gcc >= 4.9 for stdatomic.h since version 1.26.0 and
https://github.com/janet-lang/janet/commit/bfcfd58259911b92ff516bab9216831b34653805
resulting in the following build failure since commit
e066eeaff0f37ff050c77a3986cc3b7a59d4b536:

src/core/abstract.c:35:23: fatal error: stdatomic.h: No such file or directory

Fixes:
 - http://autobuild.buildroot.org/results/a2b40adb93b751221ba2cdf9a705f86c30499021

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>