package/libuhttpd: fix build with wolfssl >= 5.0
Fix the following build failure with wolfssl raised since bump to
version 5.2.0 in commit ab9912705b50bfd1a212d8192579696715cfe658 and
https://github.com/wolfSSL/wolfssl/commit/33cb8231481d5beb46b57511c2630aba36028256:

/home/buildroot/autobuild/instance-0/output-1/build/libuhttpd-3.14.1/src/ssl/openssl.c: In function 'handle_wolfssl_asn_error':
/home/buildroot/autobuild/instance-0/output-1/build/libuhttpd-3.14.1/src/ssl/openssl.c:339:10: error: 'ASN_NTRU_KEY_E' undeclared (first use in this function); did you mean 'ASN_ECC_KEY_E'?
  339 |     case ASN_NTRU_KEY_E:
      |          ^~~~~~~~~~~~~~
      |          ASN_ECC_KEY_E

Fixes:
 - http://autobuild.buildroot.org/results/3261b0035c8aadd1b62538b53e03af1cd8a7b312

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>