package/rdma-core: needs NPTL
rdma-core unconditionally uses pthread_spin_lock since its addition in
commit ce144a0bf6fbf945297d67a91125a54de87635d0 resulting in the
following build failure:

/home/autobuild/autobuild/instance-9/output-1/host/lib/gcc/sh4-buildroot-linux-uclibc/12.2.0/../../../../sh4-buildroot-linux-uclibc/bin/ld: CMakeFiles/hfi1verbs-rdmav34.dir/verbs.c.o: in function `post_recv':
verbs.c:(.text+0xc4): undefined reference to `pthread_spin_lock'

Fixes:
 - http://autobuild.buildroot.org/results/a943e03b79c4cc328b7712046ecff09706045f81

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>