package/glibmm: link with -latomic if needed
Link with -latomic if needed to avoid the following build failure since
bump to version 2.68.2 in commit
37a37edc7b858d0aecc92df966d24d95c8b25ddf:

/home/peko/autobuild/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/sparc-buildroot-linux-uclibc/9.3.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: glib/glibmm/libglibmm-2.68.so.1.3.0.p/main.cc.o: in function `Glib::Source::reference() const':
main.cc:(.text+0xd40): undefined reference to `__atomic_fetch_add_4'

Fixes:
 - http://autobuild.buildroot.org/results/6a2709956fbb16ac3cbf676acb242c88f83fcdae

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>