package/python-automat: bump to version 22.10.0
Current python-automat version 20.2.0 no longer work with Python 3.11
updated in commit 30508208d9.

Running package runtime test with command:

    support/testing/run-tests \
        -d dl \
        -o output_folder \
        tests.package.test_python_automat.TestPythonPy3Automat

Fails with output:

    Traceback (most recent call last):
      File "/root/sample_python_automat.py", line 27, in <module>
        led.turn_on()
        ^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/automat/_methodical.py", line 232, in __get__
      File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 43, in decorator
      File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 35, in copyfunction
      File "/usr/lib/python3.11/site-packages/automat/_introspection.py", line 23, in copycode
    TypeError: code() argument 13 must be str, not int

This commit fixes this issue by updating the package to the latest
version.

Signed-off-by: Julien Olivain <ju.o@free.fr>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>