package/pipewire: needs NPTL
Fix the following build failure raised since bump to version 0.3.26 in
commit e6fb2fbe435c87173e9dd6086eaae6dc6f697451 and
https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/b029000610d122ac12939d02ade2264605ff43de

thread-loop.c:(.text+0x81c): undefined reference to `pthread_setname_np'

Fixes:
 - http://autobuild.buildroot.org/results/6019f4e9676743685e8af81d60ef198c1eba1fde

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>