package/dnsmasq: fix build with ubus and without dnssec
Fix the following build failure raised since bump to version 2.86 in
commit 4109e62edc699f30ddfd2b870a0b706946f15d23:

rfc1035.c: In function 'report_addresses':
rfc1035.c:978:49: error: 'struct dnsmasq_daemon' has no member named 'workspacename'
  978 |        if (!extract_name(header, len, &p, daemon->workspacename, 1, 0))
      |                                                 ^~

Fixes:
 - http://autobuild.buildroot.org/results/51242d4f532373544e3c7ea45036b8d41390b29b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>