package/libnetconf2: disable tests
tests are not disabled since bump to version 2.0.24 in commit
6b3f00b861954fd74e426c3e30f69bd7eb78c2c6 and
https://github.com/CESNET/libnetconf2/commit/2cd716353d0922ff57c34ead58fbcd14b7fb92af
resulting in the following build failure if cmocka is found:

In file included from /home/buildroot/autobuild/instance-2/output-1/build/libnetconf2-2.0.24/tests/client/test_client_ssh.c:8:
/home/buildroot/autobuild/instance-2/output-1/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/include/cmocka.h:2334:47: error: unknown type name 'va_list'
 2334 | void vprint_message(const char* const format, va_list args) CMOCKA_PRINTF_ATTRIBUTE(1, 0);
      |                                               ^~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/fe793ae69d952a7a07d6d07e179925b67469dff4

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>