package/poppler: fix build without libpng
Fix the following build failure with libjpeg but without libpng raised
since bump to version 21.12.0 in commit
7f6f6b0588648100cd0bb8da07d078d57c24fc67:

/home/giuliobenetti/autobuild/run/instance-2/output-1/build/poppler-21.12.0/poppler/ImageEmbeddingUtils.cc:298:5: error: 'jmp_buf' does not name a type
  298 |     jmp_buf setjmpBuffer;
      |     ^~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/360972af797bb1be80b0324796794817fe0ccf53

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>