package/libgee: needs gcc >= 4.9
Fix the following build failure raised since bump to version 0.20.5
in commit ad51c1cc2f6ba38548078b91a3730e39aec5a1db and
https://gitlab.gnome.org/GNOME/libgee/-/commit/f0ccfe94ff731929e93601a38f931a12d52e5c2e:

task.c:59:1: error: initializer element is not constant
 static GOnce gee_task_data_async_pool = (GOnce) G_ONCE_INIT;
 ^

Fixes:
 - http://autobuild.buildroot.org/results/8354ea4192bcf2eb9c3be74d93b640db52ced10a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>