package/python3: requires blake2 support in openssl
Fix the following build failure raised since bump to version 3.10.1 in
commit fe973696456619f980abb7dc10b3ee242f8bb566:

/home/buildroot/autobuild/instance-3/output-1/build/python3-3.10.1/Modules/_hashopenssl.c:244:22: error: implicit declaration of function 'EVP_blake2s256'; did you mean 'LN_blake2s256'? [-Werror=implicit-function-declaration]
  244 |             digest = EVP_blake2s256();
      |                      ^~~~~~~~~~~~~~
      |                      LN_blake2s256

Fixes:
 - http://autobuild.buildroot.org/results/9112571b75aebb0ba5032ef1b16226d9848f5184

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>