package/libgpg-error: fix build issue following 1.42 bump
The build failed with gazillions of:

"gpg-error.h:1211:2: error: stray '\' in program"

This is already fixed by upstream commit
33593864cd54143db594c4237bba41e14179061c, which we backport. It is
backported as patch 0001, and the existing 0001 renamed to 0002, as it
appears later in the libgpg-error Git history.

Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>