package/python-pycli: drop package
Even with the two upstream patches added in commit
1e5a78661358f5f34fdd30f738bb8dc13cb729a5, python-pycli still raises the
following build failure since bump of python3 to version 3.10.1 in
commit fe973696456619f980abb7dc10b3ee242f8bb566 due to the new "Multiple
Exception types without parentheses" exception
(https://docs.python.org/3/whatsnew/3.10.html):

error:   File "/usr/lib/python3.10/site-packages/cli/test.py", line 142
    except raises, e:
           ^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

So drop the package as the last release was made 10 years ago.

Fixes:
 - http://autobuild.buildroot.org/results/6112e1830ce608abcea4a26b659c10e5ff09a66a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>