package/waffle: bump to version 1.7.0
This bump will fix the following build failure raised since bump of
wayland to version 1.20.0 in commit
2d49b6e1d316f362bdf31044be2af1570151c3c5 thanks to
https://gitlab.freedesktop.org/mesa/waffle/-/commit/71d46212a9d23a951d5d38f0bfd1cdf1194c8c8e
and
https://gitlab.freedesktop.org/mesa/waffle/-/commit/2c33597245bb74f19104f0a858cd40e80b26991d:

/home/giuliobenetti/autobuild/run/instance-2/output-1/host/opt/ext-toolchain/bin/../lib/gcc/powerpc64-buildroot-linux-gnu/9.3.0/../../../../powerpc64-buildroot-linux-gnu/bin/ld: ../../lib/libwaffle-1.so.0.6.1: undefined reference to `wl_proxy_get_version'
/home/giuliobenetti/autobuild/run/instance-2/output-1/host/opt/ext-toolchain/bin/../lib/gcc/powerpc64-buildroot-linux-gnu/9.3.0/../../../../powerpc64-buildroot-linux-gnu/bin/ld: ../../lib/libwaffle-1.so.0.6.1: undefined reference to `wl_proxy_marshal_flags'

https://gitlab.freedesktop.org/mesa/waffle/-/tags/v1.7.0
https://gitlab.freedesktop.org/mesa/waffle/-/tags/v1.6.3
https://gitlab.freedesktop.org/mesa/waffle/-/tags/v1.6.2

Fixes:
 - http://autobuild.buildroot.org/results/1fb1540b0ae6037140f386f44d6e17735f0674c4

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>