package/rt-tests: needs __sync_*_4 intrisics
rt-tests needs __sync_*_4 intrisics since bump to version 1.9 in commit
efd33d9517b2da7a99f3b0e76e51467823d86423 and
https://git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git/commit/?id=c86dec5765e1ad0bd1d0c429ca7c138c11da2c80:

oslat.c:(.text+0x1034): undefined reference to `__sync_add_and_fetch_4'

Fixes:
 - http://autobuild.buildroot.org/results/9b065ee7611db3a404863b85161f46a2e9e8ddad

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>