package/hiawatha: fix build with gcc 4.8
Fix the following build failure raised since commit
d5576b694c1eb2ef45e34d4f595963ec9db1c105:

/tmp/instance-1/output-1/build/hiawatha-11.1/mbedtls/library/ecjpake.c: In function 'self_test_rng':
/tmp/instance-1/output-1/build/hiawatha-11.1/mbedtls/library/ecjpake.c:973:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for( size_t i = 0; i < len; i++ )
     ^

Fixes:
 - http://autobuild.buildroot.org/results/1befc1552af91f34c600229138910c2078c2fdca

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>