package/python-scipy: fix sh4 build
Fix the following sh4 build failure raised since the addition of the
package in commit 314b2c8d47d2a6efcc5d665dbc06bcf32b7fe1d7:

INFO: sh4aeb-linux-gcc: scipy/special/_test_round.c
scipy/special/_test_round.c: In function '__pyx_pf_5scipy_7special_11_test_round_have_fenv':
scipy/special/_test_round.c:2353:30: error: 'FE_UPWARD' undeclared (first use in this function)
 2353 |     __pyx_t_1 = ((fesetround(FE_UPWARD) != 0) != 0);
      |                              ^~~~~~~~~

Retrieve debian patch as upstream doesn't want to fix this SH4 specific
issue: https://github.com/scipy/scipy/issues/15584

Fixes:
 - http://autobuild.buildroot.org/results/b82d8ed02ba5d094a0d4054e0de28e95c9d3554d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>