package/pcre2: drop JIT sparc
JIT sparc support has been dropped since version 10.41 and
https://github.com/PCRE2Project/pcre2/commit/b67d5682019fd192a615a1d5ed254b564f54126b
resulting in the following build failure since bump to version 10.42 in
commit c94237146a2addcf980745d7efa17c5618e004f3:

src/pcre2_jit_compile.c:82:2: error: #error Unsupported architecture
   82 | #error Unsupported architecture
      |  ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/d8246c9e3e54547cdb7d94dcdbf376d292dfd787

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>