package/libwebsockets: disable -Werror
Disable -Werror (enabled by default) through DISABLE_WERROR which is
available since version 4.1.0 and
https://github.com/warmcat/libwebsockets/commit/c9c152baba1fbd6e2b061b16a5c987a80309caee
to avoid the following build failure with gcc 4.8 and libev:

/usr/lfs/hdd_v1/rc-buildroot-test/scripts/instance-1/output-1/build/libwebsockets-4.3.1/lib/event-libs/libev/libev.c: In function 'lws_ev_hrtimer_cb':
/usr/lfs/hdd_v1/rc-buildroot-test/scripts/instance-1/output-1/build/libwebsockets-4.3.1/lib/event-libs/libev/libev.c:44:3: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   ev_timer_set(&ptpr->hrtimer, ((float)us) / 1000000.0, 0);
   ^

Fixes:
 - http://autobuild.buildroot.org/results/75ddbd2e0b058b69a99a2a2f01c62dedad1199c0

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>