package/zynaddsubfx: fix atomic linking
Fix the following build failure raised since the addition of the package
in commit 57bee4d47057665f24132218176b6c7be0a296ea:

/home/giuliobenetti/autobuild/run/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/riscv64-buildroot-linux-musl/10.3.0/../../../../riscv64-buildroot-linux-musl/bin/ld: libzynaddsubfx_core.a(Master.cpp.o): in function `.L1880':
Master.cpp:(.text+0x7cc0): undefined reference to `__atomic_exchange_1'

Fixes:
 - http://autobuild.buildroot.org/results/91b5959ca0eb136c1609462e71d109ff09cca5e5

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>