package/dhcp: security bump to version 4.4.3
- Security vulnerabilies will be fixed by bumping internal bind from
  9.11.14 to 9.11.36
- Drop patch (already in version)
- This bump will also fix the following build failure on platforms
  without stdatomic lock free thanks to
  https://gitlab.isc.org/isc-projects/bind9/-/commit/261c84d91d1b4581df9f7f0ec031908299de7726

  stats.c: In function 'setcounter':
  stats.c:300:29: error: 'val' undeclared (first use in this function); did you mean 'value'?
    300 |  stats->counters[counter] = val;
        |                             ^~~
        |                             value
- Update hash of license file (ISC address updated and preamble removed:
  https://gitlab.isc.org/isc-projects/dhcp/-/commit/429a56d73c0f9f2edf400fd6313850a3ce4fd809
  https://gitlab.isc.org/isc-projects/dhcp/-/commit/ee868403d0df934442a438aa6b5832bacabb7b23)

https://gitlab.isc.org/isc-projects/dhcp/-/blob/v4_4_3/RELNOTES

Fixes:
 - http://autobuild.buildroot.org/results/e4d027b5bcda852d0b5a54035de5ed37499a4ef0

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>