package/guile: Fix build failure due to missing libiconv
When building package guile with BR2_ENABLE_LOCALE=n
we get the following error:

```
In file included from filesys.c:95:
ports-internal.h:26:10: fatal error: iconv.h: No such file or directory
   26 | #include <iconv.h>
      |          ^~~~~~~~~
compilation terminated.
```

So let's fix it by selecting BR2_PACKAGE_LIBICONV and
adding libiconv package as dependency.

Signed-off-by: Pedro Aguilar <paguilar@paguilar.org>
Reviewed-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
Tested-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>