package/python-ujson: needs python3
python 2 support has been dropped since version 3.0.0 and
https://github.com/ultrajson/ultrajson/commit/0673d237cf5589a2a059771f694d5fbc5a293b13
resulting in the following build failure since bump to version 4.1.0 in
commit 2a95827e5f684e5f49c0aed8dcb621ca980ee694:

./python/ujson.c:79:15: error: variable 'moduledef' has initializer but incomplete type
   79 | static struct PyModuleDef moduledef = {
      |               ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/61cc675281ba25d6ebee4892175e9c7222aabb79

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>