package/boost: fix musl build
Fix the following build failure on musl raised since bump to version
1.78.0 in commit 1f1ce9bb27c073d099b5d06bf699238260926fa2:

In file included from libs/log/src/permissions.cpp:18:
./boost/interprocess/permissions.hpp:73:14: error: 'mode_t' in namespace '::' does not name a type
   73 |    typedef ::mode_t    os_permissions_type;
      |              ^~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/ca22263cef24b0240f7e5c374c0aeebb01ecc63e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>