package/uhd: fix build of examples
Fix the following build failure raised since the addition of the package
in commit cae3aebe5bfd234dfddd9d2789cd3e6787b38738:

../lib/libuhd.so.3.15.0: undefined reference to `int boost::math::sign<double>(double const&)'

Fixes:
 - http://autobuild.buildroot.org/results/a38856930b20a0d6fda28fe52f8a4c90c9df4e3a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>