package/zxing-cpp: needs wchar
wchar is mandatory since switch to an active fork in commit
2a31167ac6357e7ce7310324a6586e71061ddfac:

In file included from /home/autobuild/autobuild/instance-13/output-1/build/zxing-cpp-1.4.0/core/src/Result.h:12,
                 from /home/autobuild/autobuild/instance-13/output-1/build/zxing-cpp-1.4.0/core/src/GTIN.cpp:9:
/home/autobuild/autobuild/instance-13/output-1/build/zxing-cpp-1.4.0/core/src/Content.h:40:14: error: 'wstring' in namespace 'std' does not name a type
   40 |         std::wstring render(bool withECI) const;
      |              ^~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/4f97f1b291a99218f4706fce8b2934bd845755e1

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>