package/gstreamer1/gstreamer1-mm: fix build with libglib 2.68
Fix the following build failure raised since bump of libglib2 to version
2.68.1 in commit 895a3f0dffdb3a6e2dab5fd619e7ff6e10f59230:

../gstreamer/gstreamermm/register.h: In function 'GType Gst::register_mm_type(const gchar*)':
/home/buildroot/autobuild/run/instance-2/output-1/host/bin/../arm-buildroot-linux-gnueabihf/sysroot/usr/include/glib-2.0/glib/gatomic.h:117:19: error: argument 2 of '__atomic_load' must not be a pointer to a 'volatile' type
  117 |     __atomic_load (gapg_temp_atomic, &gapg_temp_newval, __ATOMIC_SEQ_CST); \
      |     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/1c75cdcc183642fd4c15d56825848b83f2ad11a5

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>