board/orangepi/orangepi-r1/genimage.cfg: fix build after move to genimage 15
Fixes:
https://gitlab.com/buildroot.org/buildroot/-/jobs/1865935239

ERROR: hdimage(sdcard.img): part boot: 'partition-type' is only valid for mbr and hybrid partition-table-type

So change to partition-type-uuid instead.  With that fixed, genimage-15 then
also complains about the overlap between the u-boot partition and the GPT:

ERROR: hdimage(sdcard.img): partition [GPT array] (offset 0x100000, size 0x4000) overlaps previous partition u-boot (offset 0x2000, size 0x102000)

So adjust the u-boot partition to end just before the GPT.

Signed-off-by: Peter Korsgaard <peter@korsgaard.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>