package/pulseaudio: alsa needs UCM
alsa needs UCM since bump to version 16.1 in commit
20d1d80c3063861fb496849d5f5d832d805b41a3 to avoid the following build
failure:

In file included from ../src/modules/alsa/alsa-mixer.h:51,
                 from ../src/modules/alsa/alsa-ucm.c:51:
../src/modules/alsa/alsa-ucm.h:26:10: fatal error: alsa/use-case.h: No such file or directory
   26 | #include <alsa/use-case.h>
      |          ^~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/c651c03bc493ac721ad6517ace550237488ef8a8

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>