package/qt5/qt5webkit: disable sampling profiler on musl
Disable sampling profiler on musl to avoid the following build falure
raised since bump to version 5.212.0-alpha4 in commit
3e892abdf03ac143fd7ab2599055c4dfd2084f1c:

/home/buildroot/autobuild/instance-0/output-1/build/qt5webkit-5.212.0-alpha4/Source/JavaScriptCore/heap/MachineStackMarker.cpp:686:2: error: #error Need a way to get the frame pointer for another thread on this platform
  686 | #error Need a way to get the frame pointer for another thread on this platform
      |  ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/87f52db7f8ebefa4c1ae3dd70d4a7a460f9aca35

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>