package/x11r7/xwayland: xlib_libxshmfence is mandatory
xlib_libxshmfence is mandatory, not optional, since the addition of the
package in commit 046e4a31de2d012858ecc6bde28f0f95999f0db2:

../miext/sync/misyncshm.c:36:10: fatal error: X11/xshmfence.h: No such file or directory
   36 | #include <X11/xshmfence.h>
      |          ^~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/cccc8f97d452ed2adbcbc4624f159a00287a3d38

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>