package/guile: disable jit on ARM with gcc < 5
jit is enabled by default since version 3.0.0 on x86-64, i686, ARMv7 and
AArch64 targets however it raises the following build failure on ARM
with gcc 4.8:

jit.c:232:1: error: initializer element is not constant
 static const jit_gpr_t THREAD = JIT_V0;
 ^

This build failure was also reported with ARM on gcc 4.9:
https://www.mail-archive.com/guile-user@gnu.org/msg11497.html

So just disable jit with ARM and gcc < 5

Fixes:
 - http://autobuild.buildroot.org/results/ba051bb00a6cad3cfd5ffeb197de20ea0eaef33e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>