package/pulseaudio: fix NLS build
Fix the following build failure with NLS raised since bump to version
16.1 in commit 20d1d80c3063861fb496849d5f5d832d805b41a3:

/home/giuliobenetti/autobuild/run/instance-3/output-1/host/lib/gcc/riscv64-buildroot-linux-uclibc/11.3.0/../../../../riscv64-buildroot-linux-uclibc/bin/ld: src/libpulsecommon-16.1.so.p/pulsecore_lock-autospawn.c.o: in function `.L0 ':
lock-autospawn.c:(.text+0x1f8): undefined reference to `libintl_dgettext'

Fixes:
 - http://autobuild.buildroot.org/results/58ce701da2896125507048b29ded75cf9bcd6e35

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>