package/python-sentry-sdk: drop httpx.py for python 2.x to fix pycompile issue
Drop httpx.py to fix the following build failure with python 2.x raised
since bump to version 1.4.3 in commit
c018cee90fb8308adb670bf90d5b739d9b4eb775 and
https://github.com/getsentry/sentry-python/commit/e2d0893824481c9a5dd3141872d90d0888c4c5f8:

error:   File "/usr/lib/python2.7/site-packages/sentry_sdk/integrations/httpx.py", line 69
    async def send(self, request, **kwargs):
            ^

Fixes:
 - http://autobuild.buildroot.org/results/fd651abb3bc2fa33c861238acf1c4ad49fdac160

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>