package/mbedtls: disable MBEDTLS_FATAL_WARNINGS
Disable MBEDTLS_FATAL_WARNINGS to avoid the following build failure
since bump to version 2.28.0 in commit
85f82a43203806dfe2535d6836d1ebb24ad27707:

/home/buildroot/autobuild/instance-0/output-1/host/arm-buildroot-linux-gnueabihf/sysroot/usr/include/features.h:412:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
  412 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/af017382bb5772de7383d71ed7b8af44717981f9

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>