package/zabbix: fix build with libressl >= 3.5.0
Fix the following build failure with libressl >= 3.5.0 raised since bump
to version 3.5.2 in commit 53c7d1353559cc2c3d9f0639e423e42e16d354c5:

tls.c:113:17: error: static declaration of 'OPENSSL_cleanup' follows non-static declaration
  113 | static void     OPENSSL_cleanup(void)
      |                 ^~~~~~~~~~~~~~~
In file included from /home/thomas/autobuild/instance-3/output-1/host/mips-buildroot-linux-gnu/sysroot/usr/include/openssl/bio.h:69,
                 from /home/thomas/autobuild/instance-3/output-1/host/mips-buildroot-linux-gnu/sysroot/usr/include/openssl/evp.h:67,
                 from /home/thomas/autobuild/instance-3/output-1/host/mips-buildroot-linux-gnu/sysroot/usr/include/openssl/hmac.h:67,
                 from /home/thomas/autobuild/instance-3/output-1/host/mips-buildroot-linux-gnu/sysroot/usr/include/openssl/ssl.h:150,
                 from ../../../include/zbxcomms.h:65,
                 from tls.c:20:
/home/thomas/autobuild/instance-3/output-1/host/mips-buildroot-linux-gnu/sysroot/usr/include/openssl/crypto.h:565:6: note: previous declaration of 'OPENSSL_cleanup' with type 'void(void)'
  565 | void OPENSSL_cleanup(void);
      |      ^~~~~~~~~~~~~~~
In file included from tls.c:20:
tls.c: In function 'zbx_log_ciphersuites':
../../../include/zbxcomms.h:222:75: error: invalid use of incomplete typedef 'SSL_CTX' {aka 'struct ssl_ctx_st'}
  222 | #       define SSL_CTX_get_ciphers(ciphers)                     ((ciphers)->cipher_list)
      |                                                                           ^~
tls.c:1415:31: note: in expansion of macro 'SSL_CTX_get_ciphers'
 1415 |                 cipher_list = SSL_CTX_get_ciphers(ciphers);
      |                               ^~~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/acdfcb17b39d438ccf5e4621707a10f60577d233

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>