package/seatd: disable -Werror
Disable -Werror to avoid the following build failure which is raised
since the addition of the package in commit
cbde5a05476a8447c920b0257b25317b02364e37

../seatd/seat.c: In function 'seat_activate_device':
../seatd/seat.c:374:48: error: unused parameter 'client' [-Werror=unused-parameter]
  374 | static int seat_activate_device(struct client *client, struct seat_device *seat_device) {
      |                                 ~~~~~~~~~~~~~~~^~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/0ec925aab23d83c52684f5fea7a4395c93a674c4

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Adrian Perez de Castro <aperez@igalia.com>
Tested-by: Adam Duskett <aduskett@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>