package/duma: fix build with gcc 11
Fix the following build failure with gcc 11:

In file included from dumapp.cpp:39:
dumapp.h:88:49: error: ISO C++17 does not allow dynamic exception specifications
   88 |     void * DUMA_CDECL operator new(DUMA_SIZE_T) throw(std::bad_alloc);
      |                                                 ^~~~~

While at it, also drop DUMA_CPP which does not seem to be set since the
addition of the package back in 2013 in commit
bda69bf4e4b642ab199ffa13c7356709885f129d

Fixes:
 - http://autobuild.buildroot.org/results/ed838a55f09841a643b05e5a7a7ca0a9d2882acd

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>