package/libdeflate: bump version to 1.15
Release notes:
https://github.com/ebiggers/libdeflate/blob/master/NEWS.md

Switch to cmake.

Added CFLAGS to fix uClibc build:

/home/bernd/buildroot/output/build/libdeflate-1.15/programs/gzip.c:367:10:
 error: 'const struct stat' has no member named 'st_atim'; did you mean 'st_atime'?

/home/bernd/buildroot/output/build/libdeflate-1.15/programs/gzip.c:367:26:
 error: 'const struct stat' has no member named 'st_mtim'; did you mean 'st_mtime'?

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>