package/imagemagick: SVG support needs host gcc >= 4.9
SVG support needs host gcc >= 4.9 since bump of harfbuzz to version
3.1.2 in commit bffecb09392e065d33a2e170ad63489379822a5a:

In file included from ../src/hb.hh:473:0,
                 from ../src/hb-buffer-serialize.cc:27:
../src/hb-vector.hh:206:20: error: 'is_trivially_copy_assignable' is not a member of 'std'
      hb_enable_if (std::is_trivially_copy_assignable<T>::value)>
                    ^

Fixes:
 - http://autobuild.buildroot.org/results/7b2430c5ae4eed51685ec12bf778c07a0a8b1701

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>