package/safeclib: bump to version 02092020
- Update indentation in hash file (two spaces)
- This bump will fix the following build failure with libest which was
  added with commit e29ded74a7d52024cc37aa1c0961858f35a0f28a:

In file included from /home/buildroot/autobuild/instance-0/output-1/host/bin/../nios2-buildroot-linux-gnu/sysroot/usr/include/libsafec/safe_lib.h:43:0,
                 from est_server_http.c:39:
/home/buildroot/autobuild/instance-0/output-1/host/bin/../nios2-buildroot-linux-gnu/sysroot/usr/include/libsafec/safe_types.h:42:9: error: unknown type name 'size_t'
 typedef size_t  rsize_t;
         ^~~~~~

https://github.com/rurban/safeclib/blob/v02092020/ChangeLog

Fixes:
 - http://autobuild.buildroot.org/results/5a12f1cb4153834078522b6068ff24ac0300d51d

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>