package/guile: fix build with glibc 2.34
Fix the following build failure with glibc 2.34 raised since bump to
version 3.0.7 in commit f9c2ae042e85dd36c0495e48db55f9b4590abe0a:

In file included from regexec.c:1368,
                 from regex.c:74:
./malloc/dynarray-skeleton.c:195:24: error: expected declaration specifiers or '...' before '(' token
  195 | __attribute_nonnull__ ((1))
      |                        ^

https://lists.gnu.org/archive/html/bug-guile/2021-08/msg00003.html

Fixes:
 - http://autobuild.buildroot.org/results/27a2a69e1177f15daec65eca035b99ea5355c34b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>