package/squid: needs threads
squid needs threads and
https://github.com/squid-cache/squid/commit/7dba4ac446341548a0b101489785f2cef9a33caa
to avoid the following build failure raised since
bump to version 5.3 in commit d7c575a68316e77dc1faa40dc4b4b7cbab245187:

ntlm_fake_auth.cc: In function 'int main(int, char**)':
ntlm_fake_auth.cc:187:18: error: 'std::this_thread' has not been declared
  187 |             std::this_thread::sleep_for(std::chrono::milliseconds(response_delay));
      |                  ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/2aabc8375d41ad4d047d20ff8ee4fe1c978e7ee1

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>