package/freeradius-server: requires MD4 in openssl
Enable MD4 in openssl to avoid the following build failure raised since
the addition of the package in commit
09fe40892a1a1565f4c5c0e350fc80b849c7d496:

In file included from src/lib/md4.c:16:
src/lib/md4.c: In function 'fr_md4_calc':
src/freeradius-devel/md4.h:76:33: error: unknown type name 'MD4_CTX'; did you mean 'FR_MD4_CTX'?
   76 | #  define FR_MD4_CTX            MD4_CTX
      |                                 ^~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/a8aa12a8129056391f975820ea3d1d62241ac051

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>