package/s6-linux-utils: fix build with glibc < 2.25
Fix the following build failure with glibc < 2.25 raised since bump to
version 2.6.0.0 in commit f3f7f1aec8eba979c2639f7460f9713f95ddf846 and
https://github.com/skarnet/s6-linux-utils/commit/ad5973028c42d947440cdae5e4f106152c3dda28:

src/minutils/rngseed.c:15:24: fatal error: sys/random.h: No such file or directory
 #include <sys/random.h>
                        ^

Fixes:
 - http://autobuild.buildroot.org/results/214bcecfc389cb412b68627c831300478d614a3a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle <arnout@mind.be>