package/audit: bump to version 3.0.6
This bump will fix the following build failure with kernel >= 5.15
thanks to
https://github.com/linux-audit/audit-userspace/commit/6b09724c69d91668418ddb3af00da6db6755208c

interpret.c:48:10: fatal error: linux/ipx.h: No such file or directory
   48 | #include <linux/ipx.h>
      |          ^~~~~~~~~~~~~

Indeed, ipx.h has been dropped since
https://github.com/torvalds/linux/commit/6c9b40844751ea30c72f7a2f92f4d704bc6b2927

https://github.com/linux-audit/audit-userspace/blob/v3.0.6/ChangeLog

Fixes:
 - http://autobuild.buildroot.org/results/1c8a959d8847d8942fbdf148c1b781df0d8bb4dc

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>