package/iperf: fix build
Fix the following build failure raised since bump to version 2.1.5 in
commit d787311f733886001248a2594fa9715c0fbba75f:

gettcpinfo.c: In function 'gettcpinfo':
gettcpinfo.c:101:42: error: expected declaration or statement at end of input
  101 | inline void gettcpinfo (int sock, struct ReportStruct *sample) {
      |                                          ^~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/073e070478f0cda34784af96bb3a802c3aac8f72

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>