package/python-libevdev: new package
python-libevdev is needed for libinput replay command:

$ libinput replay recording.yml
Error: No module named 'libevdev'
One or more python modules are missing. Please install those modules and re-run this tool.

Indeed only libinput-replay tool is a python script
(like libinput-analyze-recording, libinput-measure-fuzz...)

python-libevdev itself requires a kernel built with
CONFIG_INPUT_UINPUT option enabled, enable this option if a kernel is
built by Buildroot.

Signed-off-by: Romain Naour <romain.naour@smile.fr>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>