package/libudfread: needs __sync_*_4 or threads
libudfread needs __sync_*_4 or threads since its addition in commit
215e479c80e98b3b576415c9cfeac6e099dd89af and
https://code.videolan.org/videolan/libudfread/-/commit/06c3cb9223a3cb5ab048e42ab353958f422a8f57
to avoid the following build failure:

src/udfread.c:108:3: error: #error no atomic operation support
  108 | # error no atomic operation support
      |   ^~~~~

Fixes:
 - http://autobuild.buildroot.org/results/f76d475f49d525095ac0054224b50b9e612691d6

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>