package/xdriver_xf86-video-fbturbo: fix struct _Window::backStorage related compile failure
Add patch to fix struct _Window::backStorage related compile failure.

Since xserver commit 'dix: Remove WindowRec::backStorage ' ([1])
struct _Window::backStorage is gone, use struct _Window::backingStore instead.

Fixes:

  backing_store_tuner.c: In function 'xPostValidateTree':
  backing_store_tuner.c:112:48: error: 'struct _Window' has no member named 'backStorage'
    112 |     if (!private->ForceBackingStore && focusWin->backStorage) {
        |                                                ^~
  backing_store_tuner.c:128:20: error: 'struct _Window' has no member named 'backStorage'
    128 |         if (!curWin->backStorage && (private->ForceBackingStore ||
        |                    ^~
  backing_store_tuner.c: In function 'xReparentWindow':
  backing_store_tuner.c:161:46: error: 'struct _Window' has no member named 'backStorage'
    161 |     if (pPriorParent == pScreen->root && pWin->backStorage) {
        |                                              ^~

[1] https://gitlab.freedesktop.org/xorg/xserver/-/commit/6975807945d12c07f00e18df7fafeff43efa0267

Reported-by: Jürgen Wack <juergen.wack@gmx.de>
Signed-off-by: Peter Seiderer <ps.report@gmx.net>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>