package/pcsc-lite: link with -latomic if needed
Link with -latomic if needed to avoid the following build failure since
bump to version 1.9.6 in commit 32bc8c41371179929b1a1b505f06e02343fa6c1c
and
https://github.com/LudovicRousseau/PCSC/commit/d56ed18dbebc4423506ce7f61d3e3bcf4bdc4cb0:

/nvmedata/autobuild/instance-11/output-1/host/lib/gcc/sparc-buildroot-linux-uclibc/10.3.0/../../../../sparc-buildroot-linux-uclibc/bin/ld: pcscd-readerfactory.o: undefined reference to symbol '__atomic_fetch_add_4@@LIBATOMIC_1.0'

Fixes:
 - http://autobuild.buildroot.org/results/80b2197a37073976a7dcec7b0f92dba1b26fb3f5

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>