package/bpftool: needs headers >= 4.12
NETLINK_EXT_ACK is only available since kernel 4.12 and
https://github.com/torvalds/linux/commit/2d4bc93368f5a0ddb57c8c885cdad9c9b7a10ed5
resulting in the following build failure since addition of the package
in commit 60d2715f9f07ffdb45fa4e993cc4e29a73a61b16:

net.c: In function 'netlink_open':
net.c:110:36: error: 'NETLINK_EXT_ACK' undeclared (first use in this function); did you mean 'NETLINK_CAP_ACK'?
  110 |  if (setsockopt(sock, SOL_NETLINK, NETLINK_EXT_ACK,
      |                                    ^~~~~~~~~~~~~~~
      |                                    NETLINK_CAP_ACK

Fixes:
 - http://autobuild.buildroot.org/results/c61678e56bd73609838747048f27068818c21150

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>