package/libostree: fix build without systemd
Fix the following build failure without systemd raised since bump to
version 2022.03 in commit bf8a9a1f630b97ee818306530c109a824a527915:

src/libostree/ostree-sysroot-deploy.c: In function 'child_setup_fchdir':
src/libostree/ostree-sysroot-deploy.c:2837:19: error: 'uintptr_t' undeclared (first use in this function); did you mean 'intptr_t'?
 2837 |   int fd = (int) (uintptr_t) data;
      |                   ^~~~~~~~~
      |                   intptr_t

Fixes:
 - http://autobuild.buildroot.org/results/c134d849e7942911cb6bd13869dd2f3aefd8c21c

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>