package/dmalloc: fix strndup detection
Fix strndup detection as already done for strdup in commit
407bd3acd328b9eb54abf96cfa74b335fa224803 to avoid the following build
failure raised since bump to version 5.6.5 in commit
14ddb8a9ca0f0d5cfdc9c0a03a97ed2b216a60bc:

In file included from /nvmedata/autobuild/instance-0/output-1/host/mipsel-buildroot-linux-gnu/sysroot/usr/include/string.h:630:0,
                 from append.c:34:
dmalloc.h:396:7: error: expected identifier or '(' before '__extension__'
 char *strndup(const char *string, const DMALLOC_SIZE max_len);
       ^

Fixes:
 - http://autobuild.buildroot.org/results/2164dac43e2607a3570e8f98957a70f579d06cd3

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>