package/mpv: needs NPTL
mpv unconditionally uses pthread_getcpuclockid since version 0.33.0 and
https://github.com/mpv-player/mpv/commit/fd3caa264ea0848e7e30db94390063c87e247003
resulting in the following build failure without NPTL since commit
c327c815d98bdca27e03697379091a3ee2d9faa4:

../common/stats.c: In function 'get_thread_cpu_time_ns':
../common/stats.c:75:9: error: implicit declaration of function 'pthread_getcpuclockid'; did you mean 'pthread_getspecific'? [-Werror=implicit-function-declaration]
   75 |     if (pthread_getcpuclockid(thread, &id) == 0 &&
      |         ^~~~~~~~~~~~~~~~~~~~~
      |         pthread_getspecific

Fixes:
 - http://autobuild.buildroot.org/results/98cde5cbb0844c6ef483a75cf9a6f3fd3a46c693

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>