package/uftrace: needs NPTL
uftrace needs NPTL since its addition in commit
83bd8094ce96112b1e2b49044d50eb125e66fb9b and
https://github.com/namhyung/uftrace/commit/543fe53c256ceaef2d4d7cc44925bf1ad5a068a8:

buildroot/build/uftrace-0.10/buildroot/build/uftrace-0.10/cmds/record.c:670: undefined reference to `pthread_setname_np'

Fixes:
 - http://autobuild.buildroot.org/results/8f884efb9d45f9145a4799981157c9226390b423

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>