configs/kontron_smarc_sal28: move gpt between rcw and bootloader
genimage v15 complains about the GPT overlapping with the RCW. Move it
to offset 16k which is between the rcw (which isn't expected to grow
much more) and the bootloader.

This will fix the following error:
ERROR: hdimage(sdcard-emmc.img): partition [GPT array] (offset 0x400, size 0x4000) overlaps previous partition rcw (offset 0x1000, size 0x580)
ERROR: hdimage(sdcard-emmc.img): bootloaders, etc. that overlap with the partition table must declare the overlapping area as a hole.

Signed-off-by: Michael Walle <michael@walle.cc>
Reviewed-by: Giulio Benetti <giulio.benetti@benettiengineering.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>