package/mesa3d: DRI drivers need either glx, egl or gbm
Fixes build error:
../output-1/build/mesa3d-21.1.5/meson.build:520:4:
 ERROR: Problem encountered: building dri drivers require at least one windowing system

OSMesa is not seen as a valid windowing system for DRI drivers anymore:
https://cgit.freedesktop.org/mesa/mesa/commit/meson.build?h=21.1&id=ee802372180a2b4460cc7abb53438e45c6b6f1e4

Commit 95ac92f726541741f13c7738e2e4784fcf725c47 blindly renamed
BR2_PACKAGE_MESA3D_OSMESA_CLASSIC to BR2_PACKAGE_MESA3D_OSMESA_GALLIUM
without checking for this particular case.

Fixes:
http://autobuild.buildroot.net/results/46e3a66ddc13a064e512aad0f3afd8655889ab9d/

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>