package/iproute2: fix musl build
Fix the following musl build failure raised since bump to version 5.16.0
in commit cabf460be15c66dde606922c0d925f385de7b112:

ax25_ntop.c:5:10: fatal error: netax25/ax25.h: No such file or directory
    5 | #include <netax25/ax25.h>
      |          ^~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/455840288bbe13ed585b0e2dc7b20a294dd1eee1

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Reviewed-by: Petr Vorel <petr.vorel@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>