package/uccp420wlan: drop package
uccp420wlan is not maintained anymore (no commit since 2017) and fails
to build with any "recent" kernel (e.g. >= 4.7 which includes
https://github.com/torvalds/linux/commit/57fbcce37be7c1d2622b56587c10ade00e96afa3
or
https://github.com/torvalds/linux/commit/8552a434b6a05cc38006733afe6a239ad4d600a2):

/home/thomas/autobuild/instance-1/output-1/build/uccp420wlan-6.9.1/./src/tx.c: In function ‘uccp420wlan_tx_free_buff_req’:
/home/thomas/autobuild/instance-1/output-1/build/uccp420wlan-6.9.1/./src/tx.c:1142:49: error: ‘IEEE80211_BAND_2GHZ’ undeclared (first use in this function); did you mean ‘IEEE80211_CHAN_2GHZ’?
 1142 |                                 if (ets_band == IEEE80211_BAND_2GHZ)
      |                                                 ^~~~~~~~~~~~~~~~~~~
      |                                                 IEEE80211_CHAN_2GHZ

[...]

/home/thomas/autobuild/instance-1/output-1/build/uccp420wlan-6.9.1/./src/core.c:428:29: error: implicit declaration of function ‘ieee80211_csa_is_complete’; did you mean ‘ieee80211_scan_completed’? [-Werror=implicit-function-declaration]
  428 |                         if (ieee80211_csa_is_complete(uvif->vif))
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                             ieee80211_scan_completed

Fixes:
 - http://autobuild.buildroot.org/results/7cd7151e390b8f7a0df3e647fe4cd5d6319a830b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>