package/firmware-utils: bump to 86739f2b3ae9502368b89ef37fa6f31c42aad6f4
This bump will fix the following build failure raised since the addition
of package in commit eefb096129a3e13117dba1fb197e7a155a67f842 thanks to
https://git.openwrt.org/?p=project/firmware-utils.git;a=commit;h=f9ad6b335e0fd699398370d4c6e2e45e1c459dea
and
https://git.openwrt.org/?p=project/firmware-utils.git;a=commit;h=86739f2b3ae9502368b89ef37fa6f31c42aad6f4:

/home/giuliobenetti/autobuild/run/instance-2/output-1/host/opt/ext-toolchain/bin/../lib/gcc/powerpc64-buildroot-linux-gnu/9.3.0/../../../../powerpc64-buildroot-linux-gnu/bin/ld: CMakeFiles/ptgen.dir/src/ptgen.c.o: in function `gen_gptable':
ptgen.c:(.text+0x234): undefined reference to `bswap_64'

Fixes:
 - http://autobuild.buildroot.org/results/1e8/1e80722954fc7bd090780200b1a58b6078b601ed/build-end.log

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>