package/gensio: fix musl build
Fix the following musl build failure raised since bump to version 2.5.2
in commit bb263d0b3d5af4eed2f5d807f7c8579edd9ed5e7:

gensiotool.c:47:10: fatal error: sys/unistd.h: No such file or directory
   47 | #include <sys/unistd.h>
      |          ^~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/99a60831da94f94fdf798c1c30cc09f0e51416c7

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>