package/freeipmi: fix build with argp-standalone and NLS
Fix the following build failure with argp-standalone and NLS raised
since commit ce535c69c805e4087778308c7ede81aa8aae3fa7:

configure:14644: checking for argp_parse in -largp
configure:14669: /home/giuliobenetti/autobuild/run/instance-1/output-1/host/bin/arm-buildroot-linux-uclibcgnueabi-gcc -o conftest -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os -g0  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  conftest.c -largp  -lm -lm -lm  >&5
/home/giuliobenetti/autobuild/run/instance-1/output-1/host/lib/gcc/arm-buildroot-linux-uclibcgnueabi/10.3.0/../../../../arm-buildroot-linux-uclibcgnueabi/bin/ld: /home/giuliobenetti/autobuild/run/instance-1/output-1/host/arm-buildroot-linux-uclibcgnueabi/sysroot/usr/lib/libargp.a(argp-parse.o): in function `argp_version_parser':
/home/giuliobenetti/autobuild/run/instance-1/output-1/build/argp-standalone-1.4.1/argp-parse.c:181: undefined reference to `libintl_dgettext'

[...]

In file included from freeipmi-argp-fmtstream.c:35:
freeipmi-argp-namefrob.h:62:32: error: redefinition of 'argp_fmtstream_write'
   62 | #define __argp_fmtstream_write argp_fmtstream_write
      |                                ^~~~~~~~~~~~~~~~~~~~
freeipmi-argp-fmtstream.c:395:1: note: in expansion of macro '__argp_fmtstream_write'
  395 | __argp_fmtstream_write (argp_fmtstream_t __fs,
      | ^~~~~~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/26090162396b1b8cedfc58e1790ced528fcc35c6

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>