package/glib-networking: doesn't support libressl
glib-networking raises the following build failure with libressl:

../tls/openssl/gtlsconnection-openssl.c: In function 'g_tls_connection_openssl_handshake_thread_request_rehandshake':
../tls/openssl/gtlsconnection-openssl.c:419:27: error: 'TLS1_3_VERSION' undeclared (first use in this function); did you mean 'TLS1_2_VERSION'?
  419 |   if (SSL_version(ssl) >= TLS1_3_VERSION)
      |                           ^~~~~~~~~~~~~~
      |                           TLS1_2_VERSION
../tls/openssl/gtlsconnection-openssl.c:419:27: note: each undeclared identifier is reported only once for each function it appears in
../tls/openssl/gtlsconnection-openssl.c:420:11: error: implicit declaration of function 'SSL_key_update' [-Werror=implicit-function-declaration]
  420 |     ret = SSL_key_update (ssl, SSL_KEY_UPDATE_REQUESTED);
      |           ^~~~~~~~~~~~~~

Since libressl doesn't (intend to) support post-1.0.2 openssl
compatibility, this is only going to get worse. Therefore, require
libopenssl.

Fixes:
 - http://autobuild.buildroot.org/results/b8dea5704903c84858c7a339a73ecb713ac2791c

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>