package/php: add BR2_PACKAGE_PHP_ARCH_SUPPORTS
fiber (https://wiki.php.net/rfc/fibers) has been added in version 8.1.0
with
https://github.com/php/php-src/commit/c276c16b6627222c40bd43907475d664734b9abe

fiber uses asm on supported architectures or needs ucontext since
https://github.com/php/php-src/commit/8fd747a2a0e9f57c12bdad22a1844a736e7b4e57

As result, the following build failure is raised without ucontext_t on
architectures not supported by asm since bump to version 8.1.7 in commit
e3cf6a6a8c225201f0b87ce27025b1ae86a88508:

/home/giuliobenetti/autobuild/run/instance-3/output-1/host/lib/gcc/arc-buildroot-linux-uclibc/10.2.0/../../../../arc-buildroot-linux-uclibc/bin/ld: Zend/zend_fibers.o: in function `zend_fiber_init_context':
zend_fibers.c:(.text+0x68a): undefined reference to `getcontext'

As fiber can't be disabled (only fiber-asm), add
BR2_PACKAGE_PHP_ARCH_SUPPORTS to reflect this new dependency

Fixes:
 - http://autobuild.buildroot.org/results/f4077bae8f879828e343475318cd2ddb99e09ba4

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>