package/weston: fix build without shell-desktop
Fix the following build failure without shell-desktop raised since bump
to version 10.0.0 in commit 934a4fbb09432b35ec05f5e4d5c9acee7aea46a8 and
https://gitlab.freedesktop.org/wayland/weston/-/commit/9e90760ab054db2234f73374600489fa5584ad7c:

In file included from ../tests/weston-test-client-helper.c:43:
../tests/weston-test-client-helper.h:40:10: fatal error: weston-screenshooter-client-protocol.h: No such file or directory
   40 | #include "weston-screenshooter-client-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/8ece588f52fc1b4e422f8bce9b106d9d3822f1a1

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>