package/tcpreplay: fix build with musl-fts
Fix the following build failure with musl-fts raised since bump to
version 4.4.1 in commit 7bd79169ec394f73fe3819cd8b9ddbd0903bdc16 and
https://github.com/appneta/tcpreplay/commit/e1f4c2ac9133584da4be0da855c04c314a2e68c2:

/home/giuliobenetti/autobuild/run/instance-1/output-1/host/opt/ext-toolchain/bin/../lib/gcc/powerpc-buildroot-linux-uclibc/10.3.0/../../../../powerpc-buildroot-linux-uclibc/bin/ld: tcpreplay-tcpreplay.o: in function `main':
tcpreplay.c:(.text.startup+0x21c): undefined reference to `fts_open'

Fixes:
 - http://autobuild.buildroot.org/results/e47940b5b158395329c0132bb1bbea429c4dc249

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>