package/libbpf: add BR2_PACKAGE_LIBBPF_ARCH_SUPPORTS
libbpf does not support all architectures, for example ARM is not
supported resulting in the following build failure:

bpf.c:53:4: error: #error __NR_bpf not defined. libbpf does not support your arch.
 #  error __NR_bpf not defined. libbpf does not support your arch.
    ^

Fixes:
 - http://autobuild.buildroot.org/results/288d54100a2e736195a3a04a9e2e035d02ea5c16

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>