package/boinc: needs at least gcc 4.8 for c++11 features
Fixes:
http://autobuild.buildroot.net/results/ed3/ed3656f443364f01895600f332816d20e340f315/

hostinfo_unix.cpp:1695:37: error: range-based 'for' loops are not allowed in C++98 mode
         for (const string &ignore : ignore_list) {

Adding -std=c++11 to CXXFLAGS is done in _MAKE_OPTS due to the Makefiles
not passing CXXFLAGS from _CONV_ENV down to client/Makefile.

This is needed since bump to version 7.18.1 in commit
2b83299aea9efaa9136b88eb730ccbd222ad7c2d and
https://github.com/BOINC/boinc/commit/ed70369c091923addf5a8d64bed92c0417e91e07

Signed-off-by: Bernd Kuhls <bernd.kuhls@t-online.de>
[Peter: extend commit message as suggested by Fabrice Fontaine]
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>