package/zabbix: netsnmp needs mib
netsnmp support needs mib to avoid the following build failure raised
since the addition of the package in commit
fa113211953cf54d0c2b280acef324489001c3e5:

checks_snmp.c: In function ‘zbx_snmp_get_octet_string’:
checks_snmp.c:694:35: error: invalid use of undefined type ‘struct tree’
  694 |  hint = (NULL != subtree ? subtree->hint : NULL);
      |                                   ^~

Fixes:
 - No autobuilder failures (yet)

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>