package/omniorb: fix openssl build
Add host-pkgconf dependency to fix the following build failure with
openssl raised since commit 9d519412d65e13e4a7ffbb83edd8d1e4b2dfe4b7:

/nvmedata/autobuild/instance-25/output-1/per-package/omniorb/host/bin/m68k-buildroot-linux-uclibc-g++ -c -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os -g0  -Wall -Wno-unused -fexceptions  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -I.. -I./.. -I../../../../../include/omniORB4/internal -I../../../../../include/omniORB4/internal -D_OMNIORB_SSL_LIBRARY -D__OMNIORB4__ -I../../../../../stub -D_REENTRANT -I/usr/include -I. -I. -I../../../../../include -I../../../../../include -D__OSVERSION__=2 -D__linux__ -D__m68k__ -o static/sslActive.o sslActive.cc
m68k-buildroot-linux-uclibc-g++: WARNING: unsafe header/library path used in cross-compilation: '-I/usr/include'
In file included from /usr/include/stdlib.h:55,
                 from /usr/include/openssl/crypto.h:14,
                 from /usr/include/openssl/bio.h:20,
                 from /usr/include/openssl/ssl.h:18,
                 from ../../../../../include/omniORB4/sslContext.h:48,
                 from sslActive.cc:32:
/usr/include/bits/floatn.h:75:70: error: unknown machine mode '__TC__'
   75 | typedef _Complex float __cfloat128 __attribute__ ((__mode__ (__TC__)));
      |

Fixes:
 - http://autobuild.buildroot.org/results/47b1906eb7dd122a81191d14ad663c5931cbfade

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>