package/libks: needs NPTL
libks needs NPTL since its addition in commit
2497e3426655bcf0ff82029887e21a208dc1a2ff:

/nvmedata/autobuild/instance-17/output-1/build/libks-1.8.0/src/ks_thread.c: In function 'thread_launch':
/nvmedata/autobuild/instance-17/output-1/build/libks-1.8.0/src/ks_thread.c:237:21: error: 'pthread_setname_np' undeclared (first use in this function); did you mean 'pthread_setcanceltype'?
  237 |  if (thread->tag && pthread_setname_np)
      |                     ^~~~~~~~~~~~~~~~~~
      |                     pthread_setcanceltype

Fixes:
 - http://autobuild.buildroot.org/results/8a93b75ee51e005383eac17aa7577b43eda4cd92

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>