package/botan: fix build on mips
Fix the following build failure on one mips toolchain with gcc 5.3
raised since bump to version 2.18.2 in commit
f9ac999d4107687a6b551a4388b9286a56175aa0:

    src/lib/hash/sha3/sha3.cpp: In function 'std::tuple<long long unsigned int, long long unsigned int, long long unsigned int, long long unsigned int, long long unsigned int> Botan::{anonymous}::xor_CNs(const uint64_t*)':
    src/lib/hash/sha3/sha3.cpp:41:42: error: converting to 'std::tuple<long long unsigned int, long long unsigned int, long long unsigned int, long long unsigned int, long long unsigned int>' from initializer list would use explicit constructor 'constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {long long unsigned int, long long unsigned int, long long unsigned int, long long unsigned int, long long unsigned int}; <template-parameter-2-2> = void; _Elements = {long long unsigned int, long long unsigned int, long long unsigned int, long long unsigned int, long long unsigned int}]'
           A[4] ^ A[9] ^ A[14] ^ A[19] ^ A[24]};
                                          ^

Upstream suggested to revert a commit while they work on a better fix.
The commit to revert was a fix for XCode on Clang 12, neither of which
apply to us in Buildroot, so we can indeed just carry that revert.

Fixes:
 - http://autobuild.buildroot.org/results/4e86c3008aa70284a3002f426066fcc21d018e95

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
[yann.morin.1998@free.fr: explain why we revert]
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>