package/igd2-for-linux: bump to version 2.2
This bump will fix the build with pupnp >= 1.14.13 raised since commit
3b6bb284185c4801b0698f466b34d2a2d082330d and
https://github.com/pupnp/pupnp/commit/2f99af26731ec7d5677e5576c006a35128b59d55:

In file included from src/threadutil/FreeList.h:43,
                 from src/threadutil/TimerThread.h:39,
                 from src/gatedevice.h:32,
                 from src/gatedevice.c:38:
src/threadutil/ithread.h:917:12: error: expected ';' before 'int'
  917 | EXPORT_SPEC int pthread_mutexattr_setkind_np(
      |            ^~~~
      |            ;

Fixes:
 - http://autobuild.buildroot.org/results/2eebf8264327bd492ee8cadc0c539d42c4f2e252

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>