package/libgeos: add threads dependency
In Buildroot commit 793109ac0e9a2a782d7cb60a58c0171c5792a0b6, the
libgeos package was bumped from 3.9.1 to 3.10.1.

Since version 3.10.0, libgeos uses mutex since (commit https://github.com/libgeos/geos/commit/3fcbd1e0c52843c2ae0b4809c9f89f74ce529afe#diff-38d1bc63228770a179e474aef4fd26b1a2ab5f5758a5d98d07ac556498dd1f3d)

Toolchains without threads support fails to build:
/home/giuliobenetti/autobuild/run/instance-1/output-1/build/libgeos-3.10.1/include/geos/index/strtree/TemplateSTRtree.h:376:10: error: 'mutex' in namespace 'std' does not name a type
  376 |     std::mutex lock_;
      |          ^~~~~

So it needs threads.

Fixes:

 http://autobuild.buildroot.net/results/2d5fe2866dfa24f5747fbc826fea1108a2a6cb47/

Signed-off-by: Maxim Kochetkov <fido_max@inbox.ru>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>