package/libcap: fix build with gcc 4.8
Fix the following build failure with gcc 4.8 which is raised since bump
to version 2.51 in commit 82c4549532506055452711523570ad34f3393b10:

uns_test.c: In function 'main':
uns_test.c:118:5: error: 'for' loop initial declarations are only allowed in C99 mode
     for (int i=0; i<2; i++) {
     ^

Fixes:
 - http://autobuild.buildroot.org/results/9e67bdd540bb7779a13e27c55114a561c12b289a

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>