package/ksmbd-tools: bump to version 3.4.4
This bump will fix build failure with libkrb5 raised since the addition
of the package in commit db3db7532e8db292a6995a18878e0e805e96b7d9:

management/spnego.c:25:10: fatal error: spnego_mech.h: No such file or directory
   25 | #include "spnego_mech.h"
      |          ^~~~~~~~~~~~~~~

https://github.com/cifsd-team/ksmbd-tools/releases/tag/3.4.4

Fixes:
 - http://autobuild.buildroot.org/results/b4c3dba395327ab6ae28337efb962c99b2d5b922

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>