package/pipewire: alsa needs seq
alsa unconditionally uses seq since version 0.2.90 and
https://github.com/PipeWire/pipewire/commit/818fb9e904a3ea43ba313994e404f1b63833c548
which will result in the following build failure since commit
e6fb2fbe435c87173e9dd6086eaae6dc6f697451:

In file included from ../spa/plugins/alsa/alsa-seq-bridge.c:44:
../spa/plugins/alsa/alsa-seq.h:71:2: error: unknown type name 'snd_seq_addr_t'
   71 |  snd_seq_addr_t addr;
      |  ^~~~~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/65e3a9185b3b84ad78cd05f788f741b8734d2bbc

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>