package/libuhttpd: needs MMU
libuhttpd needs MMU since version 3.13.0 and
https://github.com/zhaojh329/libuhttpd/commit/ffdf7de3a4a1f5a62aa3814ac96e889958a30840
to avoid the following build failure raised since commit
60f7075da2ee0654374ec4dd249c1e5c627a40cf:

/home/buildroot/autobuild/instance-0/output-1/build/libuhttpd-3.14.1/src/cgi.c: In function 'create_cgi':
/home/buildroot/autobuild/instance-0/output-1/build/libuhttpd-3.14.1/src/cgi.c:321:11: error: implicit declaration of function 'fork' [-Werror=implicit-function-declaration]
  321 |     pid = fork();
      |           ^~~~

Fixes:
 - http://autobuild.buildroot.org/results/8d2a79dacf9ac423f7ece51b8c23f3683238312b

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>