package/cryptopp: disable altivec if needed
Fix the following build failure raised since commit
e625abeda1e97c3cd045a97592a680632f665c2e:

blake2s_simd.cpp:715:8: error: 'uint32x4_p' does not name a type; did you mean 'uint32_t'?
  715 | inline uint32x4_p VecLoad32(const T* p)
      |        ^~~~~~~~~~
      |        uint32_t

Fixes:
 - http://autobuild.buildroot.org/results/9e9f8559b12b8e2cf99cfab435fa7dd5796bbcd5

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Arnout Vandecappelle (Essensium/Mind) <arnout@mind.be>