package/jitterentropy-library: needs threads
Fix the following build failure raised since bump to version 3.3.1 in
commit 96fa7fe48efa4eee2c67964dc698624b73855264 and
https://github.com/smuellerDD/jitterentropy-library/commit/1e94512db65450ffd950e04fac61408b5efb7e2d

In file included from ./jitterentropy.h:98,
                 from src/jitterentropy-gcd.c:22:
./jitterentropy-base-user.h:74:10: fatal error: pthread.h: No such file or directory
   74 | #include <pthread.h>
      |          ^~~~~~~~~~~

Fixes:
 - http://autobuild.buildroot.org/results/7b01eca8f1442318dd35282605fc8815e6afb0d0

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Peter Korsgaard <peter@korsgaard.com>